monitoring_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: "{{ env_var('POSTGRES_RAW_HOST', 'postgres-raw') }}"
      port: 5432
      user: "{{ env_var('POSTGRES_RAW_USER') }}"
      password: "{{ env_var('POSTGRES_RAW_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_RAW_DB') }}"
      schema: analytics
      threads: 4
