monitoring_dbt:
  target: dev
  outputs:
    dev:
      type: postgres
      host: localhost
      port: 5433
      user: "{{ env_var('POSTGRES_RAW_USER') }}"
      password: "{{ env_var('POSTGRES_RAW_PASSWORD') }}"
      dbname: "{{ env_var('POSTGRES_RAW_DB') }}"
      schema: analytics
      threads: 4
